slides:
	pandoc index.md --embed-resources --from markdown+emoji --output index.html --slide-level 4 --standalone --to=revealjs --variable revealjs-url=https://unpkg.com/reveal.js@latest/ --variable slideNumber=true --variable theme=solarized

clean:
	rm index.html
